SNOW-1614292: java.lang.ClassNotFoundException: org.slf4j.LoggerFactor (#1862)
Fixes issue where the absence of the slf4j-api library from the classpath
results in a NoClassDefFoundError/ClassNotFoundException because
the class org.slf4j.LoggerFactory can't be found