SNOW-524708: Adding streaming ingest related metadata for streaming ingest billing (#672)
SNOW-524708

Adding streaming ingest client name and client key as part of the file metadata to support per client streaming ingest billing.

Two things to note:
1. This PR contains a few changes made by automatic google java format
2. I spent a long time trying to add a test for GCP but failed, it always complains about no permission access stage object (errors below), let me know if you know how to fix it (i believe the problem is related to presigned URL)
net.snowflake.client.jdbc.cloud.storage.StorageProviderException: com.google.cloud.storage.StorageException: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object